
PROJECT_NAME="Pedstrain Detection"

CC=gcc

all:
	@echo "Project $(PROJECT_NAME) make all"
	$(CC) -o peopleDetect *.c -lm
clean:
	@echo "Project $(PROJECT_NAME) make clean"
	rm -rf *.o
	rm -rf peopleDetect
